// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// Default [FirebaseOptions] for use with your Firebase apps.
//
// Example:
// ```dart
// import 'firebase_options.dart';
// // ...
// await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ0JYDqYWmxxYwtGn1CD1o6JUBJU_n9f8',
    appId: '1:614459056873:web:c7cd69f1f3ee77a2380678',
    messagingSenderId: '614459056873',
    projectId: 'group5-firebase-project2',
    authDomain: 'group5-firebase-project2.firebaseapp.com',
    storageBucket: 'group5-firebase-project2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNZUsKoyfcTjXgoQMpije-jNAfSIFpTXY',
    appId: '1:614459056873:android:41039bc67a4fbdc8380678',
    messagingSenderId: '614459056873',
    projectId: 'group5-firebase-project2',
    storageBucket: 'group5-firebase-project2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdwLV57WzcXKPu0RRuAnk7PPxJkjq7Iu4',
    appId: '1:614459056873:ios:f3cc14dba870c63b380678',
    messagingSenderId: '614459056873',
    projectId: 'group5-firebase-project2',
    storageBucket: 'group5-firebase-project2.appspot.com',
    iosBundleId: 'com.example.realestateMarketplaceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdwLV57WzcXKPu0RRuAnk7PPxJkjq7Iu4',
    appId: '1:614459056873:ios:f3cc14dba870c63b380678',
    messagingSenderId: '614459056873',
    projectId: 'group5-firebase-project2',
    storageBucket: 'group5-firebase-project2.appspot.com',
    iosBundleId: 'com.example.realestateMarketplaceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ0JYDqYWmxxYwtGn1CD1o6JUBJU_n9f8',
    appId: '1:614459056873:web:b4d1c1da5014d871380678',
    messagingSenderId: '614459056873',
    projectId: 'group5-firebase-project2',
    authDomain: 'group5-firebase-project2.firebaseapp.com',
    storageBucket: 'group5-firebase-project2.appspot.com',
  );
}
